version: '3.7'

services:

  backend:
    build: backend
    container_name: petka-backend
    environment:
      - JVM_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=9000
      - ENV=default
    ports:
      - '8080:8080'