/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.petka.backend;

import static org.junit.Assert.assertNotNull;

import org.junit.Test;

public class AppTest {
    //@Test
    public void testAppHasAGreeting() {
        BackendApplication classUnderTest = new BackendApplication();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
