/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package org.petka.backend;

/**
 * Auto generated test class.
 */
public class AppTest {

    //@Test
    public void testAppHasAGreeting() {
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
